### ISSUE TITLE
chromedriver crashes when trying to run - docker-compose up

### ISSUE THREAD

**Issue by derek-palmer** [derek-palmer/volt-analytics#17]
```
jupyter_1  | Traceback (most recent call last):
jupyter_1  |   File "/home/tools/acquireData.py", line 22, in <module>
jupyter_1  |     driver = webdriver.Chrome(chrome_options=chromeOptions)
jupyter_1  |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
jupyter_1  |     desired_capabilities=desired_capabilities)
jupyter_1  |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 140, in __init__
jupyter_1  |     self.start_session(desired_capabilities, browser_profile)
jupyter_1  |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 229, in start_session
jupyter_1  |     response = self.execute(Command.NEW_SESSION, parameters)
jupyter_1  |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
jupyter_1  |     self.error_handler.check_response(response)
jupyter_1  |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
jupyter_1  |     raise exception_class(message, screen, stacktrace)
jupyter_1  | selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed
jupyter_1  |   (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Linux 4.9.36-moby x86_64)
```

**Comment by derek-palmer** [comment]
Looks to be a bug with docker + chrome, after multiple attempts to fix with no resolution. I moved the selenium script that requires chrome and the chromedriver to the root and will depend on it running on the host machine (for now)
